#!/usr/bin/env python3
"""Compile the static frontend in public/ into eliza_web/assets.py.

Vercel's Python app-mode only bundles Python modules reachable via imports, not
arbitrary directories like public/. So we embed the frontend as a Python module
(imported by the serverless handler) — the same mechanism that reliably bundles
the DOCTOR scripts.

Edit the files in public/ and re-run:  python scripts/build_assets.py
"""

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
PUBLIC = ROOT / "public"
OUT = ROOT / "eliza_web" / "assets.py"

# route path -> source filename in public/
FILES = {
    "/index.html": "index.html",
    "/style.css": "style.css",
    "/app.js": "app.js",
}


def build():
    lines = [
        '"""Auto-generated by scripts/build_assets.py — do not edit by hand.',
        "",
        "The static frontend (public/) embedded as strings so Vercel bundles it",
        "with the Python function. Edit public/ and re-run the build script.",
        '"""',
        "",
        "ASSETS = {",
    ]
    for route, name in FILES.items():
        content = (PUBLIC / name).read_text(encoding="utf-8")
        # ensure_ascii=False keeps non-ASCII (umlauts, emoji) as real UTF-8
        # characters; surrogate-pair \uXXXX escapes would not round-trip through
        # a Python string literal.
        lines.append(f"    {json.dumps(route)}: {json.dumps(content, ensure_ascii=False)},")
    lines.append("}")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    build()
